# Unique identifier for this project in SonarQube
sonar.projectKey=task-manager-frontend
sonar.projectName=Task Manager Frontend

# Source files to analyze
sonar.sources=src

# Exclude test files from static analysis if you add them later
sonar.exclusions=src/**/*.test.jsx,src/**/*.test.js

# Languages to analyze
sonar.language=js
