apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
# In Kubernetes/OKD, secret data must be base64 encoded.
# echo -n 'devops_user' | base64 -> ZGV2b3BzX3VzZXI=
# echo -n 'devops_password' | base64 -> ZGV2b3BzX3Bhc3N3b3Jk
data:
  database-user: ZGV2b3BzX3VzZXI=
  database-password: ZGV2b3BzX3Bhc3N3b3Jk
